### ISSUE TITLE
Parameter ensure failed on Package[mongodb_server]: Provider must have features 'versionable' to set 'ensure' to '2.6.11-1'

### ISSUE THREAD

**Issue by jengstrom** [neillturner/puppet-mongodb_ops_manager#2]
Getting the following error when running spec tests.

Failure/Error: it { is_expected.to compile.with_all_deps }
       error during compilation: Parameter ensure failed on Package[mongodb_server]: Provider must have features 'versionable' to set 'ensure' to '2.6.11-1' at ~/workspace/puppet/site/profiles/spec/fixtures/modules/mongodb/manifests/server/install.pp:29

**Comment by jengstrom** [comment]
Perhaps its something like this?

https://github.com/elastic/puppet-elasticsearch/issues/44

**Comment by neillturner** [comment]
This is the puppetlabs  mongodb which a dependency. 
maybe it is how i am calling it, maybe i can only set the version number under specify conditions, or maybe it is an issue with the puppetlabs-mongodb module, don't know.  
quite happy to take a PR for this but no time to investigate myself so closing.
