### ISSUE TITLE
Paths

### ISSUE THREAD

**Issue by jengstrom** [neillturner/puppet-mongodb_ops_manager#3]
Looks like /usr/bin nor /bin is not in $PATH in my env by default.  Can you please update the code (manifests/application.pp) to include the path or allow me to push to a branch?

exec { 'download-mms-onprem':
    command     => "curl -OL https://downloads.mongodb.com/on-prem-mms/rpm/mongodb-mms-${version}.x86_64.rpm",
    cwd         => '/tmp',
    path        => '/usr/bin:$PATH',
    environment => ["https_proxy=${https_proxy}"],
    creates     => "/tmp/mongodb-mms-${version}.x86_64.rpm",
    require     => File_line['/etc/sudoers']
  }

  exec { "rpm --install /tmp/mongodb-mms-${version}.x86_64.rpm":
    command => "rpm --install /tmp/mongodb-mms-${version}.x86_64.rpm",
    path    => '/bin:$PATH',
    cwd     => '/tmp',
    unless  => "rpm -q mongodb-mms-${version}",
    require => Exec['download-mms-onprem']
  }

**Comment by neillturner** [comment]
Well i deliberately don't set paths. I guess I expect people in the initial manifest file (site.pp (or whatever they call it) to set the path so common things like curl and rpm are accessible. 
e.g.: 
node default {
  Exec {
    path => ["/bin", "/sbin", "/usr/bin", "/usr/sbin"],
  }

**Comment by neillturner** [comment]
closed fixed in version 0.1.3
